import Head from 'next/head';
import { playerData } from '../../data/data';
import Image from 'next/image';

export default function PlayerPage({ player }) {
  return (
    <div>
      <Head>
      <title>{player.legendName}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
        <meta name="msapplication-TileColor" content="#da532c" />
        <meta name="theme-color" content="#ffffff" />
      </Head>

      <div className="flex justify-center">
        <div className='grid items-center justify-center gap-6 pt-20 md:pt-10 md:pb-12 lg:pt-8 lg:pb-10 max-w-3xl'>
        <div className="flex-1 space-y-4">
          <Image src={player.photo} alt={player.legendName}/>
          <h1 className="inline-block text-4xl font-extrabold tracking-tight text-slate-900 lg:text-5xl">{player.legendName}</h1>
          <p className="text-xl text-slate-600">{player.nationality}</p>
        </div>

        <hr className="py-0 border-slate-200" />

        <div className="flex-1 space-y-10">
          <div>
            <h2 className="text-xl font-bold tracking-tighter sm:text-3xl md:text-4xl pb-3">Major Trophies</h2>
            <ul>
              {Object.entries(player.trophies).map(([trophy, number]) => (
                <li key={trophy} className='py-0.5'>
                  <strong>{trophy}</strong>: {number}
                </li>
              ))}
            </ul>
          </div>          
          <div className='space-y-3'>
            <h2 className="text-xl font-bold tracking-tighter sm:text-3xl md:text-4xl">Notable moments</h2>
            <p className="text-lg text-slate-600">{player.description.notableMoments}</p>
            <p className="text-lg text-slate-600">{player.description.whyFamous}</p>
          </div>
          <div className='space-y-3'>
            <h2 className="text-xl font-bold tracking-tighter sm:text-3xl md:text-4xl">Teams Played</h2>
            <p className="text-lg text-slate-600">{player.description.teamsPlayed}</p>
          </div>
          <div className='space-y-3'>
            <h2 className="text-xl font-bold tracking-tighter sm:text-3xl md:text-4xl">Playing Style</h2>
            <p className="text-lg text-slate-600">{player.description.playingStyle}</p>
          </div>
        </div>
        </div>
      </div>
    </div>
  );
}

export async function getStaticPaths() {
  const paths = playerData.map((player) => ({
    params: { id: player.legendId.toString() },
  }));

  return { paths, fallback: false };
}

export async function getStaticProps({ params }) {
  const player = playerData.find((player) => player.legendId.toString() === params.id);

  return {
    props: {
      player,
    },
  };
}