import Head from 'next/head'
import Image from 'next/image'
import { playerData } from '../../data/data';
import { useRouter } from 'next/router';

const IndividualFootballer = () => {
  const router = useRouter();
  const { id } = router.query;

  return (
    <div>
      <Head>
        <title>FVG</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
        <meta name="msapplication-TileColor" content="#da532c" />
        <meta name="theme-color" content="#ffffff" />
      </Head>
      
      <div className='md:px-20 lg:px-20 pb-8 md:py-0 lg:py-0 h-auto'>
        <p className='text-3xl text-black'>{id}</p>
      </div> 
    </div>
  )
}

export default IndividualFootballer;