import Head from 'next/head'
import Image from 'next/image'

import LegendaryPlayers from '../public/legend-images/legends.png';
import Link from 'next/link';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Goat Voting</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="container grid items-center justify-center gap-6 pt-20 pb-8 md:pt-10 md:pb-12 lg:pt-3 lg:pb-10">
        <Image src={LegendaryPlayers} width={800} height={450} alt='alt' priority={true}/>
        <div className="flex flex-col items-start gap-4 lg:w-[52rem]">
          <h1 className="text-3xl font-bold leading-[1.1] tracking-tighter sm:text-5xl md:text-6xl">
            The G.O.A.T Voting 
          </h1>
          <p className="max-w-[42rem] leading-normal text-slate-700 sm:text-xl sm:leading-8">
            G.O.A.T stands for greatest of all time. Is it Messi or Ronaldo?
          </p>
        </div>
        <div className="flex gap-4">
          <Link href="auth/Login" legacyBehavior>
            <a
              className="inline-flex items-center justify-center text-sm font-medium transition-colors focus:outline-none focus:ring-2 focus:ring-offset-2 disabled:opacity-50 disabled:pointer-events-none data-[state=open]:bg-slate-100 bg-slate-900 text-white hover:bg-slate-700 h-11 px-8 rounded-md"              
            >
              Vote Now
            </a>
          </Link>
          <a
            target="_blank"
            rel="noreferrer"
            className="inline-flex items-center justify-center text-sm font-medium transition-colors focus:outline-none focus:ring-2  disabled:opacity-50 disabled:pointer-events-none data-[state=open]:bg-slate-100 bg-transparent border border-slate-200 hover:bg-slate-100 h-11 px-8 rounded-md"
            href="https://github.com/dunyanong/GoatVote"
          >
            GitHub
          </a>
        </div>
      </section>

    </div>
  )
}
