import Head from "next/head";

const Ranking = () => {
    return (
        <div>
            <Head>
                <title>Goat Voting</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
                <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
                <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
                <link rel="manifest" href="/site.webmanifest" />
                <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
                <meta name="msapplication-TileColor" content="#da532c" />
                <meta name="theme-color" content="#ffffff" />
            </Head>
            
            <div className="mx-auto flex flex-col items-start gap-4 lg:w-[52rem]">
                <h1 className="text-3xl font-bold leading-[1.1] tracking-tighter sm:text-5xl md:text-6xl">Ranking in Progress...</h1>
            
            </div>
        </div>
    );
}
 
export default Ranking;