import Head from "next/head";

const Ranking = () => {
    return (
        <div>
            <Head>
                <title>Goat Voting</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            
            <div className="mx-auto flex flex-col items-start gap-4 lg:w-[52rem]">
                <h1 className="text-3xl font-bold leading-[1.1] tracking-tighter sm:text-5xl md:text-6xl">Ranking in Progress...</h1>
            
            </div>
        </div>
    );
}
 
export default Ranking;